# Generated by Django 3.1.2 on 2020-10-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='deposit_value',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='withdrawal_value',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
