# Generated by Django 3.1.2 on 2020-10-05 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20201005_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='deposit_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='withdrawal_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
